In [ ]:
import duckdb
import pandas as pd

# Connect to the local database file
con = duckdb.connect("../data/raw/transfermarkt-datasets.duckdb")

# List all tables in the database
con.sql("SHOW TABLES").df()

# Four Important Tables:
# 1. players: one row per player (contains general player data as well as market value so must remove that)
# 2. appearances: one row = one player appearing in one match (game stats are here)
# 3. games: tells us which season each match belongs to
# 4. player_valuations: historical market value records for different players during a particular season

                 name
0         appearances
1          club_games
2               clubs
3        competitions
4           countries
5         game_events
6        game_lineups
7               games
8      national_teams
9   player_valuations
10            players
11          transfers
12            version

In [5]:
con.sql("SELECT * FROM players LIMIT 5").df()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,agent_name,image_url,international_caps,international_goals,current_national_team_id,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,<NA>,<NA>,None,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000,30000000
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,<NA>,<NA>,None,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000,8000000
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,<NA>,<NA>,None,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000,34500000
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,https://img.a.transfermarkt.technology/portrai...,<NA>,<NA>,None,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus FC,200000,24500000
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,IFM,https://img.a.transfermarkt.technology/portrai...,<NA>,<NA>,None,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,Bayern Munich,100000,3000000

In [35]:
con.sql("SELECT * FROM appearances WHERE player_name='Bukayo Saka'").df()

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
0,3098764_433177,3098764,433177,2740,11,2018-11-29,Bukayo Saka,EL,0,0,0,0,22
1,3098800_433177,3098800,433177,11,11,2018-12-13,Bukayo Saka,EL,0,0,0,0,90
2,3050357_433177,3050357,433177,11,11,2019-01-01,Bukayo Saka,GB1,0,0,0,0,7
3,3136614_433177,3136614,433177,1181,11,2019-01-05,Bukayo Saka,FAC,0,0,0,0,4
4,3252424_433177,3252424,433177,11,11,2019-09-19,Bukayo Saka,EL,0,0,1,2,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,4626157_433177,4626157,433177,11,11,2026-05-10,Bukayo Saka,GB1,1,0,0,0,80
299,4626158_433177,4626158,433177,11,11,2026-05-18,Bukayo Saka,GB1,0,0,0,1,90
300,4776621_433177,4776621,433177,3299,11,2026-06-17,Bukayo Saka,FIWC,0,0,0,1,18
301,4776645_433177,4776645,433177,3299,11,2026-06-23,Bukayo Saka,FIWC,0,0,0,0,25
302,4776669_433177,4776669,433177,3299,11,2026-06-27,Bukayo Saka,FIWC,0,0,0,1,63

In [6]:
con.sql("SELECT * from games LIMIT 5").df()

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
0,1026846,FIWC,2009,Round of 16,2010-06-26,3449,3589,2,1,<NA>,...,Nelson Mandela Bay Stadium,30597,Wolfgang Stark,https://www.transfermarkt.co.uk/spielbericht/i...,None,None,Uruguay,South Korea,2:1,national_team_competition
1,1026847,FIWC,2009,Round of 16,2010-06-27,3437,6303,3,1,<NA>,...,FNB-Stadium,84377,Roberto Rosetti,https://www.transfermarkt.co.uk/spielbericht/i...,None,None,Argentina,Mexico,3:1,national_team_competition
2,1027001,FIWC,2009,Round of 16,2010-06-26,3505,3441,1,2,<NA>,...,Royal Bafokeng Stadium,34976,Viktor Kassai,https://www.transfermarkt.co.uk/spielbericht/i...,None,None,United States,Ghana,1:2,national_team_competition
3,1027002,FIWC,2009,Round of 16,2010-06-27,3262,3299,4,1,<NA>,...,Free State Stadium,40510,Jorge Larrionda,https://www.transfermarkt.co.uk/spielbericht/i...,None,None,Germany,England,4:1,national_team_competition
4,1027048,FIWC,2009,Round of 16,2010-06-28,3379,3503,2,1,<NA>,...,Moses Mabhida Stadion,61962,Undiano Mallenco,https://www.transfermarkt.co.uk/spielbericht/i...,None,None,Netherlands,Slovakia,2:1,national_team_competition

In [41]:
con.sql("SELECT * FROM player_valuations LIMIT 5").df()

,player_id,date,market_value_in_eur,current_club_name,current_club_id,player_club_domestic_competition_id
0,405973,2000-01-20,150000,Unknown,3057,BE1
1,342216,2001-07-20,100000,Unknown,1241,SC1
2,3132,2003-12-09,400000,Dynamo Kyiv,126,TR1
3,6893,2003-12-15,900000,Galatasaray,984,GB1
4,10,2004-10-04,7000000,SV Werder Bremen,398,IT1

In [50]:
# Load data
player_valuations = con.sql("SELECT * FROM player_valuations").df()

# For each player+season, find the valuation closest to end of season (June 30)
player_valuations["season_end"] = pd.to_datetime(
    player_valuations["date"].dt.year.where(
        player_valuations["date"].dt.month >= 7,
        player_valuations["date"].dt.year - 1
    ).astype(str) + "-06-30"
)

# Add a season column to valuations (season = year the season started)
player_valuations["season"] = player_valuations["date"].dt.year.where(
    player_valuations["date"].dt.month >= 7,
    player_valuations["date"].dt.year - 1
)

# player_valuations[player_valuations['player_id'] == 433177]

# Sort and take the last valuation within each player+season window
end_of_season_value = (
    player_valuations
    .sort_values("date")
    .groupby(["player_id", "season"])
    .last()  # latest record within the season window
    .reset_index()
    [["player_id", "season", "season_end", "market_value_in_eur"]]
)

end_of_season_value[end_of_season_value['player_id'] == 433177]

        player_id  season season_end  market_value_in_eur
238296     433177    2019 2019-06-30             20000000
238297     433177    2020 2020-06-30             65000000
238298     433177    2021 2021-06-30             65000000
238299     433177    2022 2022-06-30            120000000
238300     433177    2023 2023-06-30            140000000
238301     433177    2024 2024-06-30            150000000
238302     433177    2025 2025-06-30            110000000

In [59]:
# Load data
appearances = con.sql("SELECT * FROM appearances").df()
players = con.sql("SELECT * FROM players").df()
games = con.sql("SELECT * from games").df()

# game_id is an int in appearances but str in games, they need to match before merging
games["game_id"] = games["game_id"].astype("int32")

# Add season to appeaarances by joining on game_id
appearances_2 = appearances.merge(games, on="game_id", how="inner")
season_stats = (
    appearances_2
    .groupby(["player_id", "season"])
    .agg(
        minutes=("minutes_played", "sum"),
        goals=("goals", "sum"),
        assists=("assists", "sum")
    )
)
season_stats["goals_per_90"] = season_stats["goals"] / season_stats["minutes"] * 90
season_stats["assists_per_90"] = season_stats["assists"] / season_stats["minutes"] * 90

season_stats = season_stats.reset_index()

season_stats = season_stats.merge(
    players[["player_id", "name", "position", "date_of_birth"]],
    on="player_id",
    how="inner"
)

season_stats["season"] = season_stats["season"].astype(int)

season_stats = season_stats.merge(end_of_season_value, on=["player_id", "season"], how="inner")

# checking nulls (only found 50 in date of birth column)
# season_stats.isna().sum()
# season_stats[season_stats.isna().any(axis=1)]

season_stats = season_stats.dropna(subset=["date_of_birth"])

season_stats["age"] = (
    (season_stats["season_end"] - season_stats["date_of_birth"]).dt.days / 365.25
).astype(int)

season_stats[season_stats['player_id'] == 433177]

,player_id,season,minutes,goals,assists,goals_per_90,assists_per_90,name,position,date_of_birth,season_end,market_value_in_eur,age
73599,433177,2019,2569,4,10,0.140132,0.350331,Bukayo Saka,Attack,2001-09-05,2019-06-30,20000000,17
73600,433177,2020,3433,7,10,0.183513,0.262161,Bukayo Saka,Attack,2001-09-05,2020-06-30,65000000,18
73601,433177,2021,3084,11,7,0.321012,0.204280,Bukayo Saka,Attack,2001-09-05,2021-06-30,65000000,19
73602,433177,2022,3768,15,11,0.358280,0.262739,Bukayo Saka,Attack,2001-09-05,2022-06-30,120000000,20
73603,433177,2023,3841,20,14,0.468628,0.328040,Bukayo Saka,Attack,2001-09-05,2023-06-30,140000000,21
73604,433177,2024,2500,12,13,0.432000,0.468000,Bukayo Saka,Attack,2001-09-05,2024-06-30,150000000,22
73605,433177,2025,3279,11,11,0.301921,0.301921,Bukayo Saka,Attack,2001-09-05,2025-06-30,110000000,23

In [ ]:
appearances.sort_values("date", ascending=False)

,appearance_id,game_id,player_id,player_club_id,player_current_club_id,date,player_name,competition_id,yellow_cards,red_cards,goals,assists,minutes_played
1894349,4776668_989069,4776668,989069,3563,15300,2026-06-28,Jakhongir Urozov,FIWC,0,0,0,0,82
1894270,4776666_369567,4776666,369567,3383,413,2026-06-28,Sasa Kalajdzic,FIWC,0,0,1,0,1
1894257,4776666_120205,4776666,120205,3383,167,2026-06-28,Michael Gregoritsch,FIWC,0,0,0,1,45
1894258,4776666_127573,4776666,127573,3383,39,2026-06-28,Phillipp Mwene,FIWC,0,0,0,0,90
1894259,4776666_171424,4776666,171424,3614,18487,2026-06-28,Riyad Mahrez,FIWC,0,0,2,0,90
...,...,...,...,...,...,...,...,...,...,...,...,...,...
20,2235545_80073,2235545,80073,317,11282,2012-07-05,Glynor Plet,ELQ,0,0,2,1,90
21,2235545_84260,2235545,84260,317,403,2012-07-05,Nicky Kuiper,ELQ,0,0,0,0,64
22,2235769_75109,2235769,75109,11907,2227,2012-07-05,Célio Santos,ELQ,0,0,0,0,90
23,2235777_63496,2235777,63496,3811,4128,2012-07-05,Vladimirs Kamess,ELQ,0,0,0,0,75
0,2231978_38004,2231978,38004,853,235,2012-07-03,Aurélien Joachim,CLQ,0,0,2,0,90

In [21]:
games[games["game_id"] == "4776666"]

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
87205,4776666,FIWC,2025,Group J,2026-06-28,3614,3383,3,3,<NA>,...,GEHA Field at Arrowhead Stadium,69045,Ilgiz Tantashev,https://www.transfermarkt.co.uk/spielbericht/i...,4-3-3 Attacking,4-2-3-1,Algeria,Austria,3:3,national_team_competition

In [28]:
games.sort_values("season", ascending=False)

,game_id,competition_id,season,round,date,home_club_id,away_club_id,home_club_goals,away_club_goals,home_club_position,...,stadium,attendance,referee,url,home_club_formation,away_club_formation,home_club_name,away_club_name,aggregate,competition_type
81518,4634477,L1,2025,30. Matchday,2026-04-19,27,79,4,2,1,...,Allianz Arena,75000,Sören Storks,https://www.transfermarkt.co.uk/bayern-munich_...,4-2-3-1,3-4-2-1,Bayern Munich,VfB Stuttgart,4:2,domestic_league
82400,4641425,NL1,2025,5. Matchday,2025-09-13,1435,724,3,0,11,...,De Adelaarshorst,10003,Serdar Gözübüyük,https://www.transfermarkt.co.uk/go-ahead-eagle...,4-3-3 Defending,4-3-3 Defending,Go Ahead Eagles,FC Volendam,3:0,domestic_league
82398,4641423,NL1,2025,2. Matchday,2025-08-17,132,385,2,1,8,...,Rat Verlegh Stadion,20012,Martin van den Kerkhof,https://www.transfermarkt.co.uk/nac-breda_fort...,4-3-3 Defending,4-3-3 Defending,NAC Breda,Fortuna Sittardia Combinatie,2:1,domestic_league
82397,4641422,NL1,2025,2. Matchday,2025-08-17,724,1090,2,2,12,...,Kras Stadion,6376,Martijn Vos,https://www.transfermarkt.co.uk/fc-volendam_az...,4-3-3 Defending,4-3-3 Defending,FC Volendam,AZ Alkmaar,2:2,domestic_league
82396,4641421,NL1,2025,2. Matchday,2025-08-17,468,200,2,1,10,...,Sparta-stadion - Het Kasteel,10040,Allard Lindhout,https://www.transfermarkt.co.uk/sparta-rotterd...,4-3-3 Defending,4-3-3 Defending,Sparta Rotterdam,FC Utrecht,2:1,domestic_league
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88837,49320,FIWC,2005,Group E,2006-06-17,3376,3505,1,1,<NA>,...,Fritz-Walter-Stadion,46000,Jorge Larrionda,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Italy,United States,1:1,national_team_competition
88836,49319,FIWC,2005,Group B,2006-06-15,3557,3581,1,0,<NA>,...,Olympiastadion Berlin,72000,Lubos Michel,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Sweden,Paraguay,1:0,national_team_competition
88835,49318,FIWC,2005,Group B,2006-06-15,3299,7149,2,0,<NA>,...,Max-Morlock-Stadion,41000,Toru Kamikawa,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,England,Trinidad and Tobago,2:0,national_team_competition
88833,49316,FIWC,2005,Group A,2006-06-14,3262,3442,1,0,<NA>,...,SIGNAL IDUNA PARK,65000,Luis Medina Cantalejo,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Germany,Poland,1:0,national_team_competition
88847,49331,FIWC,2005,Group H,2006-06-19,3807,3699,0,4,<NA>,...,Volksparkstadion,50000,Graham Poll,https://www.transfermarkt.co.uk/spielbericht/i...,NaN,NaN,Saudi Arabia,Ukraine,0:4,national_team_competition

In [29]:
competiion = con.sql("SELECT * from competitions").df()
competiion[competiion["competition_id"] == "NL1"]
# competiion

,competition_id,competition_code,name,sub_type,type,country_id,country_name,domestic_league_code,confederation,total_clubs,url
39,NL1,eredivisie,eredivisie,first_tier,domestic_league,122,Netherlands,NL1,europa,18,https://www.transfermarkt.co.uk/eredivisie/sta...

In [40]:
saka = player_valuations[player_valuations["player_id"] == 433177]
saka['date'].unique()

<DatetimeArray>
['2019-09-23 00:00:00', '2019-12-10 00:00:00', '2020-03-09 00:00:00',
 '2020-04-08 00:00:00', '2020-07-30 00:00:00', '2020-10-13 00:00:00',
 '2021-03-18 00:00:00', '2021-05-28 00:00:00', '2021-12-23 00:00:00',
 '2022-06-15 00:00:00', '2022-09-15 00:00:00', '2022-11-03 00:00:00',
 '2022-12-23 00:00:00', '2023-03-16 00:00:00', '2023-06-20 00:00:00',
 '2023-12-19 00:00:00', '2024-03-14 00:00:00', '2024-05-27 00:00:00',
 '2024-12-16 00:00:00', '2025-05-30 00:00:00', '2025-10-17 00:00:00',
 '2025-12-09 00:00:00', '2026-03-09 00:00:00', '2026-06-03 00:00:00']
Length: 24, dtype: datetime64[us]

In [42]:
saka

,player_id,date,market_value_in_eur,current_club_name,current_club_id,player_club_domestic_competition_id
304996,433177,2019-09-23,7000000,Arsenal FC,11,GB1
309545,433177,2019-12-10,13000000,Arsenal FC,11,GB1
326435,433177,2020-03-09,22000000,Arsenal FC,11,GB1
338261,433177,2020-04-08,20000000,Arsenal FC,11,GB1
345532,433177,2020-07-30,35000000,Arsenal FC,11,GB1
355521,433177,2020-10-13,40000000,Arsenal FC,11,GB1
381252,433177,2021-03-18,60000000,Arsenal FC,11,GB1
387463,433177,2021-05-28,65000000,Arsenal FC,11,GB1
419577,433177,2021-12-23,65000000,Arsenal FC,11,GB1
450245,433177,2022-06-15,65000000,Arsenal FC,11,GB1
463329,433177,2022-09-15,70000000,Arsenal FC,11,GB1
469653,433177,2022-11-03,90000000,Arsenal FC,11,GB1
484465,433177,2022-12-23,100000000,Arsenal FC,11,GB1
490666,433177,2023-03-16,110000000,Arsenal FC,11,GB1
507430,433177,2023-06-20,120000000,Arsenal FC,11,GB1
536627,433177,2023-12-19,120000000,Arsenal FC,11,GB1
547323,433177,2024-03-14,130000000,Arsenal FC,11,GB1
552139,433177,2024-05-27,140000000,Arsenal FC,11,GB1
582286,433177,2024-12-16,150000000,Arsenal FC,11,GB1
598565,433177,2025-05-30,150000000,Arsenal FC,11,GB1
617038,433177,2025-10-17,140000000,Arsenal FC,11,GB1
621191,433177,2025-12-09,130000000,Arsenal FC,11,GB1
636505,433177,2026-03-09,120000000,Arsenal FC,11,GB1
651414,433177,2026-06-03,110000000,Arsenal FC,11,GB1